# yaml-language-server : $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: RAYX
site_url: https://hz-b.github.io/rayx/
repo_url: https://github.com/hz-b/rayx
site_author: Helmholtz-Zentrum Berlin für Materialien und Energie (HZB)
site_description: RAYX is a powerful, multi-component simulation platform designed to streamline the design and optimization of beamlines in synchrotron light source facilities.
copyright: ©HZB 2025

# nav entry overwritten by awesome-nav plugin which allows folders and provides globs, see: .nav.yml

plugins:
  - search
  - awesome-nav:
      filename: .nav.yml
  - mkdoxy:
      enabled: !ENV [ENABLE_MKDOXY, True]
      save-api: .mkdoxy
      # full-doc: True
      # debug: False
      # ignore-errors: False
      projects:
        rayxCore: # using rayx-core as project name resulted in errors when using snippets
          src-dirs: Intern/rayx-core/src
          full-doc: True
          # doxy-cfg-file: Intern/rayx-core/doc/doxyfile
          doxy-cfg:
            FILE_PATTERNS: "*.h"
            RECURSIVE: True
            GENERATE_XML: True  # needed by mkdoxy, otherwise the build will crash
  - mike:
      canonical_version: latest

extra:
  version:
    provider: mike

theme:
  name: material
  logo: res/rayx-logo_48x48.png
  favicon: res/rayx-logo_48x48.png
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - navigation.tabs.sticky
    - navigation.sections
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      # primary: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      # primary: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.tabbed:
      alternate_style: true
      # combine_header_slug: true
  - pymdownx.details            # collapsible admonitions with ???
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  # Maybe needed for MkDoxy snippets?
  - pymdownx.blocks.html:
  - pymdownx.blocks.definition:
  - pymdownx.blocks.tab:


extra_javascript:
  - js/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

