name: Deploy Documentation
on:
  push:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-docs:
    name: Build and publish documentation
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v5 # normally fetches only the triggering commit
        with:
          fetch-depth: 0 # fetches all commits and tags for all branches
          # TODO: this is probably way too much, only needs the current commit with tags and gh-pages branch for mike version.info

      - name: Set up Python # according to the uv documentation this is faster that letting uv manage python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv # use the same dependencies locally and in the CI
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Install docs dependencies
          # TODO: --locked asserts that the lockfile remains unchanged should this use --frozen instead?
        run: |
          uv sync --group docs --locked
          sudo apt-get update
          sudo apt-get install --yes doxygen

      - name: Setup Git Credentials
        run: |
          git config --global user.name "CI Deploy (Mike)"
          git config --global user.email "bot@example.com"

      - name: Build and deploy dev documentation
        # overwrites dev version and includes the git hash in the display name
        # --push defaults to gh-pages branch
        run: uv run mike deploy --push dev --title="dev ($(git rev-parse --short HEAD))"

      - name: Build and deploy release documentation
        # Build / overwrite one version per major (tagged) version of RAYX with the full version as title and alias "latest"
        # Pushing tag v.1.2.3 will overwrite the current v.1 and will be displayed as v.1.2.3 and becomes the default version
        # Pushing tag v.2.0.0 will not overwrite the v.1, but will become the default "latest"
        if: startsWith(github.ref, 'refs/tags/v') # commit is a tagged release v*
        env:
          VERSION: ${{ github.ref_name }} # this should be the tag name, e.g "v6.6.6"
        run: |
          uv run mike deploy --push --update-aliases ${VERSION/.*} --title=$VERSION latest
