name: testNix

on:
  push:
    branches:
      - '**'     # Run on all branches
    tags-ignore:
      - 'v*'     # Ignore tag pushes matching 'v*'
  pull_request:
    branches:
      - '**'     # Run for all pull requests

env:
  rml: Intern/rayx-core/tests/input/METRIX_U41_G1_H1_318eV_PS_MLearn_v114.rml

jobs:
  nix-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [rayx, rayx-cuda]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@v3

      - name: Enable Nix flakes
        run: |
          mkdir -p ~/.config/nix
          echo "experimental-features = nix-command flakes" >> ~/.config/nix/nix.conf

      - name: nix build
        run: |
          nix build .#${{ matrix.target }}
          ./result/bin/${{ matrix.target }} -x -c -V -i ${{env.rml}}

      - name: nix run
        run: |
          nix run .#${{ matrix.target }} -- -x -c -V -i ${{env.rml}}

      - name: nix shell
        run: |
          nix shell .#${{ matrix.target }}
          ${{ matrix.target }} -x -c -V -i ${{env.rml}}
