name: testNix

on:
  push:
    branches:
      - '**'     # Run on all branches
    tags-ignore:
      - 'v*'     # Ignore tag pushes matching 'v*'
  pull_request:
    branches:
      - '**'     # Run for all pull requests

env:
  rml: Intern/rayx-core/tests/input/METRIX_U41_G1_H1_318eV_PS_MLearn_v114.rml

jobs:
  nix:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [rayx, rayx-cuda, rayx-tests, rayx-ui, rayx-docker, rayx-cuda-docker]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@v3

      - name: Enable Nix flakes
        run: |
          mkdir -p ~/.config/nix
          echo "experimental-features = nix-command flakes" >> ~/.config/nix/nix.conf

      - name: build
        run: |
          nix build .#${{ matrix.target }}

      - name: run rayx (cli)
        if: matrix.target == 'rayx' || matrix.target == 'rayx-cuda'
        run: |
          nix run .#${{ matrix.target }} -- -V ${{ env.rml }}

      - name: print test results
        if: matrix.target == 'rayx-tests'
        run: |
          cat ./result/rayx-core-tst.log

      - name: tag docker images
        if: matrix.target == 'rayx-docker' || matrix.target == 'rayx-cuda-docker'
        run: |
          docker load < result
          image_name=${{ matrix.target }}
          image_name=${x%-docker}
          docker image tag "${image_name}:untagged" "rayx:${{ github.sha }}"
