name: Test Documentation Build --strict
on:
  pull_request:
    branches:
      - '**'     # Run for all pull requests
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# dont automatically update the uv lockfile (equivalent to --locked),
# manage dependencies explicitly with: uv lock --upgrade
env:
  UV_LOCKED: true

jobs:
  deploy-docs:
    name: Test mkdocs build
    runs-on: ubuntu-latest

    steps:

      - name: Checkout current branch
        uses: actions/checkout@v5

      - name: Set up Python # according to the uv documentation this is faster that letting uv manage python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv # use the same dependencies locally and in the CI
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Install docs dependencies
        run: |
          uv sync --group docs
          sudo apt-get update
          sudo apt-get install --yes doxygen

      - name: Build unversioned docs --strict
        run: uv run mkdocs build --strict
