name: testNix

on:
  push:
    branches:
      - '**'     # Run on all branches
    tags-ignore:
      - 'v*'     # Ignore tag pushes matching 'v*'
  pull_request:
    branches:
      - '**'     # Run for all pull requests

env:
  rml: Intern/rayx-core/tests/input/METRIX_U41_G1_H1_318eV_PS_MLearn_v114.rml

jobs:
  nix-build-run-shell:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [rayx, rayx-cuda, rayx-tests]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@v3

      - name: Enable Nix flakes
        run: |
          mkdir -p ~/.config/nix
          echo "experimental-features = nix-command flakes" >> ~/.config/nix/nix.conf

      - name: nix build
        if: matrix.target != 'rayx-tests'
        run: |
          nix build .#${{ matrix.target }}
          ./result/bin/rayx -V ${{ env.rml }}

      - name: run rayx
        if: matrix.target != 'rayx-tests'
        run: |
          nix run .#${{ matrix.target }} -- -V ${{ env.rml }}

      - name: run tests
        if: matrix.target == 'rayx-tests'
        run: |
          nix build .#rayx-tests
          cat ./result/rayx-core-tst.log

      # - name: nix shell
      #   run: |
      #     nix shell .#${{ matrix.target }}
      #     valgrind --error-exitcode=42 rayx -V ${{ env.rml }}
      #     exit # exit the nix shell
